### PR TITLE
Bugfix for leaderboard command

### PR DESCRIPTION
**Pull request by einsatzbereit**
The `[-1]` gets the guild if from the the database entry. If you want to tag a user at this point, with the given database structure, you need to get the user id by `[1]`

### CODE REVIEW

**Comment by xezzz** [comment]
Hey there,
this isn't a bug. ``[-1]`` gets the last element in a list, meaning in a 2-element list it does the same thing as ``[1]``.
Thanks for looking through the code anyway, I always appreciate it :D

**Comment by einsatzbereit** [comment]
Also always got „Unkown User#0000“ wird the -1. I was working after i changed ist to 1. Strange. I will habe a look on it again.

**Comment by einsatzbereit** [comment]
- First command with `1`
- Second and Third with `-1`
  -  As you can see i get the `Unknown#0000`
image

**Comment by einsatzbereit** [comment]
My first guess was a caching problem or the db connection, but the Total XP also came from the db and is the correct string.

**Pull request closed without merging**
